export const mockReports = [
  {
    "equipmentTag": "DNY_111-PKPG-0100",
    "vibrationStatus": "Degraded - Tier 2",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Degraded - Tier 2",
    "facility": "FPSO DNY",
    "system": "Power Generation",
    "tagNumber": "DNY_111-PKPG-0100",
    "cmmsNumber": "CMMS-9115",
    "cof": "High",
    "location": "Module 1 - Power",
    "machineName": "Main Power Generator A",
    "mcProtection": "Overspeed & Vib Trip",
    "operatingContext": "Main Power Generation",
    "technology": "Vibration Analysis",
    "component": "Drive End Bearing",
    "raisedBy": "Roberto Santos",
    "raisedDate": "2026-08-14",
    "targetDate": "2026-09-14",
    "shortDescription": "1X and 2X harmonic vibration increase on generator DE bearing",
    "woNumber": "801021335",
    "conditionAssessment": "Velocity spectrum shows 1X harmonic peak reaching 4.8 mm/s RMS under 80% generator electrical load.",
    "longDescription": "Schedule laser shaft realignment between turbine gearbox output and generator DE shaft during next planned shutdown.",
    "equipmentClass": "Gas Turbine Generator",
    "subunit": "Generator Rotor",
    "maintainableItem": "DE Rolling Element Bearing",
    "failureModeDescription": "VIB - Vibration",
    "failureMechanismSubdivision": "Mechanical Failure - Unbalance",
    "createdAt": "2026-08-14T10:00:00Z"
  },
  {
    "equipmentTag": "DNY_115-PUCE-9501-A",
    "vibrationStatus": "Good - Tier 4",
    "lubeOilStatus": "Critical - Tier 1",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Critical - Tier 1",
    "facility": "FPSO DNY",
    "system": "Oil & Process",
    "tagNumber": "DNY_115-PUCE-9501-A",
    "cmmsNumber": "CMMS-9104",
    "cof": "High",
    "location": "Module 4 - Boiler",
    "machineName": "Boiler Main Feed Water Pump A",
    "mcProtection": "Temp & Vib Trip",
    "operatingContext": "Steam Generation",
    "technology": "Lube Oil Analysis",
    "component": "Thrust Bearing Reservoir",
    "raisedBy": "Julia Mendes",
    "raisedDate": "2026-08-20",
    "targetDate": "2026-09-05",
    "shortDescription": "Severe metallic particle contamination and ISO cleanliness code degradation (22/19/16)",
    "woNumber": "801021320",
    "conditionAssessment": "Spectrometric analysis shows copper (Cu > 45 ppm) and iron (Fe > 80 ppm) indicating severe thrust bearing shoe wear.",
    "longDescription": "Perform immediate emergency bearing inspection, filter cartridge replacement, and offline lube oil flushing.",
    "equipmentClass": "Centrifugal Pump",
    "subunit": "Lubrication Circuit",
    "maintainableItem": "Lube Oil",
    "failureModeDescription": "OHE - Overheating",
    "failureMechanismSubdivision": "Material Failure - Wear",
    "createdAt": "2026-08-20T10:00:00Z"
  },
  {
    "equipmentTag": "UNY_771-PKGC-0100",
    "vibrationStatus": "Critical - Tier 1",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Critical - Tier 1",
    "facility": "FPSO UNY",
    "system": "Gas Compression",
    "tagNumber": "UNY_771-PKGC-0100",
    "cmmsNumber": "CMMS-9082",
    "cof": "High",
    "location": "Module 3 - Gas",
    "machineName": "Main Gas Compressor A",
    "mcProtection": "Vibration Trip",
    "operatingContext": "Continuous Gas Export",
    "technology": "Vibration Analysis",
    "component": "Axial Thrust Sensor",
    "raisedBy": "Gustavo Silva",
    "raisedDate": "2026-08-18",
    "targetDate": "2026-09-10",
    "shortDescription": "High axial displacement jump without corresponding casing vibration increase",
    "woNumber": "801021309",
    "conditionAssessment": "Axial probe channel A shows intermittent -18V DC bias voltage spikes indicating loose probe connector in terminal head.",
    "longDescription": "Inspect probe cabling integrity, re-tighten BNC connectors at local junction box, and verify gap voltage with multimeter.",
    "equipmentClass": "Centrifugal Compressor",
    "subunit": "Instrumentation & Protection",
    "maintainableItem": "Proximity Probe",
    "failureModeDescription": "AIR - Abnormal Instrument Reading",
    "failureMechanismSubdivision": "Instrument Failure - Drift",
    "createdAt": "2026-08-18T10:00:00Z"
  },
  {
    "equipmentTag": "PTY_662-PUCE-0030-A",
    "vibrationStatus": "Degraded - Tier 2",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Degraded - Tier 2",
    "facility": "FPSO PTY",
    "system": "Oil & Process",
    "tagNumber": "PTY_662-PUCE-0030-A",
    "cmmsNumber": "CMMS-9140",
    "cof": "Medium",
    "location": "Module 5 - Oil",
    "machineName": "Crude Oil Pump A",
    "mcProtection": "Pressure Trip",
    "operatingContext": "Crude Offloading",
    "technology": "Vibration Analysis",
    "component": "Mechanical Seal Housing",
    "raisedBy": "Carlos Eduardo",
    "raisedDate": "2026-08-12",
    "targetDate": "2026-09-12",
    "shortDescription": "High frequency cavitation floor noise detected on pump suction impeller",
    "woNumber": "801021342",
    "conditionAssessment": "Ultrasonic spectrum reveals broadband noise in 5 kHz - 20 kHz band matching suction strainer partial blockage.",
    "longDescription": "Switch to standby pump B, isolate pump A, and clean suction basket strainer to restore proper NPSHa.",
    "equipmentClass": "Centrifugal Pump",
    "subunit": "Shaft Sealing",
    "maintainableItem": "Mechanical Seal",
    "failureModeDescription": "NOI - Abnormal Noise",
    "failureMechanismSubdivision": "Mechanical Failure - Cavitation",
    "createdAt": "2026-08-12T10:00:00Z"
  },
  {
    "equipmentTag": "ONE_111-PKPD-6100",
    "vibrationStatus": "Good - Tier 4",
    "lubeOilStatus": "Degraded - Tier 2",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Degraded - Tier 2",
    "facility": "FPSO ONE",
    "system": "Power Generation",
    "tagNumber": "ONE_111-PKPD-6100",
    "cmmsNumber": "CMMS-9155",
    "cof": "High",
    "location": "Module 2 - Essential Power",
    "machineName": "Emergency Generator",
    "mcProtection": "Low Oil Pressure Trip",
    "operatingContext": "Emergency Power Standby",
    "technology": "Lube Oil Analysis",
    "component": "Engine Crankcase",
    "raisedBy": "Fernanda Lima",
    "raisedDate": "2026-08-15",
    "targetDate": "2026-09-15",
    "shortDescription": "Viscosity drop from 15W40 to 11.2 cSt at 100C caused by unburned fuel dilution",
    "woNumber": "801021350",
    "conditionAssessment": "FTIR flash point test indicates 3.5% diesel fuel dilution from injector leakage during cold standby testing.",
    "longDescription": "Inspect diesel fuel injectors for nozzle dripping, test pop-off pressure, and perform complete oil change.",
    "equipmentClass": "Diesel Engine Generator",
    "subunit": "Engine Block",
    "maintainableItem": "Engine Oil",
    "failureModeDescription": "PLU - Parameter Deviation",
    "failureMechanismSubdivision": "Fluid Degradation - Fuel Dilution",
    "createdAt": "2026-08-15T10:00:00Z"
  },
  {
    "equipmentTag": "PTY_111-PKPG-0100",
    "vibrationStatus": "Good - Tier 4",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Degraded - Tier 2",
    "overallCondition": "Degraded - Tier 2",
    "facility": "FPSO PTY",
    "system": "Power Generation",
    "tagNumber": "PTY_111-PKPG-0100",
    "cmmsNumber": "CMMS-9160",
    "cof": "High",
    "location": "Module 1 - Power",
    "machineName": "Main Power Generation 1",
    "mcProtection": "Thermal Trip",
    "operatingContext": "Main Power Generation",
    "technology": "Thermography Analysis",
    "component": "Generator Terminal Box",
    "raisedBy": "Luciana Costa",
    "raisedDate": "2026-08-16",
    "targetDate": "2026-09-16",
    "shortDescription": "Phase U terminal connection delta T of +32C relative to adjacent phases",
    "woNumber": "801021360",
    "conditionAssessment": "Infrared thermogram shows phase U cable lug operating at 78C while phases V and W operate at 46C.",
    "longDescription": "De-energize bus at next window, check torque with calibrated torque wrench, and re-apply conductive grease.",
    "equipmentClass": "Gas Turbine Generator",
    "subunit": "Electrical Stator Connection",
    "maintainableItem": "Phase Busbar Lug",
    "failureModeDescription": "OHE - Overheating",
    "failureMechanismSubdivision": "Electrical Failure - High Resistance Joint",
    "createdAt": "2026-08-16T10:00:00Z"
  },
  {
    "equipmentTag": "DNY_116-PURO-0003-A",
    "vibrationStatus": "Good - Tier 3",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Good - Tier 3",
    "facility": "FPSO DNY",
    "system": "Oil & Process",
    "tagNumber": "DNY_116-PURO-0003-A",
    "cmmsNumber": "CMMS-9170",
    "cof": "Medium",
    "location": "Module 6 - Fuel",
    "machineName": "MGO Transfer Pump A",
    "mcProtection": "Vibration Alarm",
    "operatingContext": "MGO Fuel Bunkering",
    "technology": "Vibration Analysis",
    "component": "Flexible Coupling",
    "raisedBy": "Julia Mendes",
    "raisedDate": "2026-08-25",
    "targetDate": "2026-09-25",
    "shortDescription": "2X running speed peak dominance indicating angular coupling misalignment",
    "woNumber": "801021370",
    "conditionAssessment": "Axial vibration on pump DE bearing exhibits 2X running speed harmonic at 2.9 mm/s RMS.",
    "longDescription": "Verify pump and motor base bolt torques and check coupling elastomeric insert for wear.",
    "equipmentClass": "Screw Pump",
    "subunit": "Coupling Assembly",
    "maintainableItem": "Coupling Insert",
    "failureModeDescription": "VIB - Vibration",
    "failureMechanismSubdivision": "Mechanical Failure - Misalignment",
    "createdAt": "2026-08-25T10:00:00Z"
  },
  {
    "equipmentTag": "ONE_111-PKPG-0100A",
    "vibrationStatus": "Good - Tier 4",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Good - Tier 4",
    "facility": "FPSO ONE",
    "system": "Power Generation",
    "tagNumber": "ONE_111-PKPG-0100A",
    "cmmsNumber": "CMMS-9180",
    "cof": "High",
    "location": "Module 1 - Power",
    "machineName": "Power Generation Packages A",
    "mcProtection": "Lube Oil Temp Trip",
    "operatingContext": "Continuous Power Generation",
    "technology": "Lube Oil Analysis",
    "component": "Turbine Reduction Gearbox",
    "raisedBy": "Fernanda Lima",
    "raisedDate": "2026-08-26",
    "targetDate": "2026-09-26",
    "shortDescription": "Moisture content below 100 ppm following centrifuge separator optimization",
    "woNumber": "801021380",
    "conditionAssessment": "Water content Karl Fischer test confirmed 65 ppm, TAN 0.18 mg KOH/g, within pristine operational envelope.",
    "longDescription": "Continue routine monthly surveillance sampling and maintain centrifuge operational temperature at 75C.",
    "equipmentClass": "Gas Turbine Generator",
    "subunit": "Gearbox",
    "maintainableItem": "Synthetic Gear Oil",
    "failureModeDescription": "PLU - Parameter Deviation",
    "failureMechanismSubdivision": "Fluid Degradation - Water Ingress",
    "createdAt": "2026-08-26T10:00:00Z"
  },
  {
    "equipmentTag": "UNY_111-PKPG-0100",
    "vibrationStatus": "Degraded - Tier 2",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Degraded - Tier 2",
    "facility": "FPSO UNY",
    "system": "Power Generation",
    "tagNumber": "UNY_111-PKPG-0100",
    "cmmsNumber": "CMMS-9190",
    "cof": "High",
    "location": "Module 1 - Power",
    "machineName": "Main Power Generator A",
    "mcProtection": "Vibration Trip",
    "operatingContext": "Base Load Power Generation",
    "technology": "Vibration Analysis",
    "component": "Drive End Radial Bearing",
    "raisedBy": "Roberto Santos",
    "raisedDate": "2026-08-22",
    "targetDate": "2026-09-22",
    "shortDescription": "Subsynchronous peak at 0.43X running speed on turbine DE bearing",
    "woNumber": "801021390",
    "conditionAssessment": "Orbit plot indicates slight elliptical distortion with subsynchronous energy emerging at low discharge pressure.",
    "longDescription": "Verify lube oil supply temperature (maintain at 45C minimum) and check lube oil supply pressure to tilting pad bearings.",
    "equipmentClass": "Gas Turbine Generator",
    "subunit": "Tilting Pad Bearing",
    "maintainableItem": "Bearing Pad",
    "failureModeDescription": "VIB - Vibration",
    "failureMechanismSubdivision": "Hydrodynamic Instability - Oil Whirl",
    "createdAt": "2026-08-22T10:00:00Z"
  },
  {
    "equipmentTag": "DNY_111-PKPD-0400",
    "vibrationStatus": "Good - Tier 4",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 3",
    "overallCondition": "Good - Tier 3",
    "facility": "FPSO DNY",
    "system": "Power Generation",
    "tagNumber": "DNY_111-PKPD-0400",
    "cmmsNumber": "CMMS-9200",
    "cof": "Medium",
    "location": "Module 2 - Essential Gen",
    "machineName": "Essential Generator No3",
    "mcProtection": "Thermal Overload",
    "operatingContext": "Essential Power Standby",
    "technology": "Thermography Analysis",
    "component": "Control Panel Breaker Contact",
    "raisedBy": "Julia Mendes",
    "raisedDate": "2026-08-27",
    "targetDate": "2026-09-27",
    "shortDescription": "Minor temperature elevation on ACB auxiliary terminal connection",
    "woNumber": "801021400",
    "conditionAssessment": "ACB primary contact temperatures uniform at 38C; auxiliary contact block shows localized +8C gradient.",
    "longDescription": "Clean auxiliary contact surfaces with electrical contact cleaner and re-seat terminal block.",
    "equipmentClass": "Power Generator",
    "subunit": "Switchgear Module",
    "maintainableItem": "Air Circuit Breaker (ACB)",
    "failureModeDescription": "OHE - Overheating",
    "failureMechanismSubdivision": "Electrical Failure - Contact Oxidation",
    "createdAt": "2026-08-27T10:00:00Z"
  },
  {
    "equipmentTag": "ONE_771-PKGC-0100A",
    "vibrationStatus": "Critical - Tier 1",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Critical - Tier 1",
    "facility": "FPSO ONE",
    "system": "Process Utilities",
    "tagNumber": "ONE_771-PKGC-0100A",
    "cmmsNumber": "CMMS-9210",
    "cof": "High",
    "location": "Module 3 - Gas Compression",
    "machineName": "Main Gas Compessor A",
    "mcProtection": "Vibration & Axial Trip",
    "operatingContext": "Main Gas Compression",
    "technology": "Vibration Analysis",
    "component": "High Speed Pinion Gear",
    "raisedBy": "Fernanda Lima",
    "raisedDate": "2026-08-23",
    "targetDate": "2026-09-08",
    "shortDescription": "Gear mesh frequency sideband modulation indicating tooth surface spalling",
    "woNumber": "801021410",
    "conditionAssessment": "GMF at 1840 Hz with sidebands spaced at pinion rotational speed (48.5 Hz) reaching 12 g peak acceleration.",
    "longDescription": "Perform borescope visual inspection of high-speed pinion teeth through inspection port; prepare spare gear set.",
    "equipmentClass": "Gas Compressor",
    "subunit": "Speed Increaser Gearbox",
    "maintainableItem": "Helical Pinion Gear",
    "failureModeDescription": "VIB - Vibration",
    "failureMechanismSubdivision": "Material Failure - Surface Fatigue",
    "createdAt": "2026-08-23T10:00:00Z"
  },
  {
    "equipmentTag": "PTY_111-PKPD-5100",
    "vibrationStatus": "Good - Tier 4",
    "lubeOilStatus": "Good - Tier 4",
    "thermographyStatus": "Good - Tier 4",
    "overallCondition": "Good - Tier 4",
    "facility": "FPSO PTY",
    "system": "Power Generation",
    "tagNumber": "PTY_111-PKPD-5100",
    "cmmsNumber": "CMMS-9220",
    "cof": "Low",
    "location": "Module 2 - Essential Gen",
    "machineName": "Essential Generator No 1",
    "mcProtection": "Vibration Alarm",
    "operatingContext": "Essential Generator Surveillance",
    "technology": "Vibration Analysis",
    "component": "Engine Foundation Skids",
    "raisedBy": "Carlos Eduardo",
    "raisedDate": "2026-08-26",
    "targetDate": "2026-09-26",
    "shortDescription": "Structural baseline vibration verified within ISO 10816-6 Zone A envelope",
    "woNumber": "801021420",
    "conditionAssessment": "Overall skid velocity levels recorded at 1.4 mm/s RMS under 100% resistive load bank testing.",
    "longDescription": "Log baseline spectrum as reference for upcoming bi-annual surveillance routine.",
    "equipmentClass": "Power Generator",
    "subunit": "Structural Baseframe",
    "maintainableItem": "Anti-Vibration Mounts",
    "failureModeDescription": "VIB - Vibration",
    "failureMechanismSubdivision": "Mechanical Verification - Normal",
    "createdAt": "2026-08-26T10:00:00Z"
  }
];
