import { db } from './index';
import { equipments, equipmentHistory, analysisReports, workOrders } from './schema';

const initialEquipments = [
  // FPSO UNY (Gas System)
  {
    tag: 'COCE_TIME_NRS_01',
    fpso: 'UNY',
    name: 'Compressor Performance',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '23/07/2026, 12:47:04',
    observation: 'Operating normally.',
  },
  {
    tag: 'COCE_TIME_NRS_02',
    fpso: 'UNY',
    name: 'Compressor Performance',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'High',
    objectType: 'NCE',
    condition: 'Critical - Tier 1',
    vibrationStatus: 'Critical',
    lubeOilStatus: 'Good',
    lastUpdate: '22/07/2026, 14:10:00',
    observation: 'High vibration alarm triggered on axial sensors.',
  },
  {
    tag: 'COCE_TIME_NRS_03',
    fpso: 'UNY',
    name: 'Compressor Performance',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'Medium',
    objectType: 'SECE',
    condition: 'Degraded - Tier 2',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Degraded',
    lastUpdate: '20/07/2026, 09:30:00',
    observation: 'Lube oil level slightly below nominal.',
  },
  {
    tag: 'COCE_TIME_NRS_04',
    fpso: 'UNY',
    name: 'Compressor Performance',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'Medium',
    objectType: 'NCE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '18/07/2026, 16:20:00',
    observation: 'Inspection scheduled for upcoming maintenance window.',
  },
  {
    tag: 'COCE_TIME_NRS_05',
    fpso: 'UNY',
    name: 'Compressor Performance',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'Low',
    objectType: 'NCE',
    condition: 'Good - Tier 3',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '15/07/2026, 11:05:00',
    observation: 'No issues reported.',
  },
  
  // FPSO UNY (Turbines & Pumps)
  {
    tag: 'TURB_METH_GDS_01',
    fpso: 'UNY',
    name: 'Turbine Performance',
    class: 'TURB - Turbine, Gas',
    system: 'Gas',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '24/07/2026, 10:20:15',
    observation: 'Operating under normal parameters.',
  },
  {
    tag: 'TURB_METH_GDS_02',
    fpso: 'UNY',
    name: 'Turbine Performance',
    class: 'TURB - Turbine, Gas',
    system: 'Gas',
    criticality: 'Medium',
    objectType: 'SECE',
    condition: 'Degraded - Tier 2',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Degraded',
    lastUpdate: '21/07/2026, 11:35:40',
    observation: 'Increased exhaust temperature readings.',
  },
  {
    tag: 'PUMP_COOL_AUX_01',
    fpso: 'UNY',
    name: 'Cooling Water Pump',
    class: 'PUMP - Centrifugal Pump',
    system: 'Water',
    criticality: 'Low',
    objectType: 'NCE',
    condition: 'Good - Tier 3',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '19/07/2026, 08:00:00',
    observation: 'Seal oil pressure stable.',
  },
  {
    tag: 'PUMP_COOL_AUX_02',
    fpso: 'UNY',
    name: 'Cooling Water Pump',
    class: 'PUMP - Centrifugal Pump',
    system: 'Water',
    criticality: 'Medium',
    objectType: 'SECE',
    condition: 'Critical - Tier 1',
    vibrationStatus: 'Critical',
    lubeOilStatus: 'Degraded',
    lastUpdate: '23/07/2026, 07:15:00',
    observation: 'Cavitation noise detected in primary impeller.',
  },

  // FPSO CDI (Gas, Oil & Water Systems)
  {
    tag: 'CDI_COMP_MAIN_01',
    fpso: 'CDI',
    name: 'Main Gas Compressor A',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '22/07/2026, 15:45:00',
    observation: 'Recommissioned after scheduled overhaul.',
  },
  {
    tag: 'CDI_COMP_MAIN_02',
    fpso: 'CDI',
    name: 'Main Gas Compressor B',
    class: 'COCE - Compressor, Centrifugal',
    system: 'Gas',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Degraded - Tier 2',
    vibrationStatus: 'Degraded',
    lubeOilStatus: 'Good',
    lastUpdate: '20/07/2026, 18:10:00',
    observation: 'Vibration frequency spectral spike at 2X RPM.',
  },
  {
    tag: 'CDI_PUMP_OIL_01',
    fpso: 'CDI',
    name: 'Crude Oil Transfer Pump A',
    class: 'PUMP - Screw Pump',
    system: 'Oil',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 3',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '17/07/2026, 14:00:00',
    observation: 'Flow output aligned with specification.',
  },
  {
    tag: 'CDI_PUMP_OIL_02',
    fpso: 'CDI',
    name: 'Crude Oil Transfer Pump B',
    class: 'PUMP - Screw Pump',
    system: 'Oil',
    criticality: 'Medium',
    objectType: 'NCE',
    condition: 'Critical - Tier 1',
    vibrationStatus: 'Critical',
    lubeOilStatus: 'Critical',
    lastUpdate: '24/07/2026, 13:20:00',
    observation: 'High bearing temperature & particle contamination.',
  },
  {
    tag: 'CDI_GEN_TURB_01',
    fpso: 'CDI',
    name: 'Main Power Generator Turb-A',
    class: 'TURB - Gas Turbine Generator',
    system: 'Power',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '21/07/2026, 09:00:00',
    observation: 'Generator load 85% nominal, thermal imaging normal.',
  },
  {
    tag: 'CDI_GEN_TURB_02',
    fpso: 'CDI',
    name: 'Main Power Generator Turb-B',
    class: 'TURB - Gas Turbine Generator',
    system: 'Power',
    criticality: 'Medium',
    objectType: 'NCE',
    condition: 'Degraded - Tier 2',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Degraded',
    lastUpdate: '16/07/2026, 11:30:00',
    observation: 'Water content in lube oil sample exceeds threshold.',
  },
  {
    tag: 'CDI_WATER_INJ_01',
    fpso: 'CDI',
    name: 'Water Injection Pump 1',
    class: 'PUMP - Multistage Centrifugal',
    system: 'Water',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '24/07/2026, 16:00:00',
    observation: 'High pressure discharge stable.',
  },
  {
    tag: 'CDI_WATER_INJ_02',
    fpso: 'CDI',
    name: 'Water Injection Pump 2',
    class: 'PUMP - Multistage Centrifugal',
    system: 'Water',
    criticality: 'Low',
    objectType: 'NCE',
    condition: 'Machine Off',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '10/07/2026, 08:00:00',
    observation: 'Standby unit, currently offline.',
  },

  // FPSO SEP (Separation, Gas & Power Systems)
  {
    tag: 'SEP_COMP_BOOST_01',
    fpso: 'SEP',
    name: 'Gas Booster Compressor',
    class: 'COCE - Reciprocating Compressor',
    system: 'Gas',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '23/07/2026, 11:15:00',
    observation: 'Suction pressure controlled.',
  },
  {
    tag: 'SEP_COMP_BOOST_02',
    fpso: 'SEP',
    name: 'Gas Booster Compressor B',
    class: 'COCE - Reciprocating Compressor',
    system: 'Gas',
    criticality: 'Medium',
    objectType: 'NCE',
    condition: 'Degraded - Tier 2',
    vibrationStatus: 'Degraded',
    lubeOilStatus: 'Good',
    lastUpdate: '18/07/2026, 17:40:00',
    observation: 'Piston rod packing seal temperature elevated.',
  },
  {
    tag: 'SEP_SEP_HEATER_01',
    fpso: 'SEP',
    name: 'First Stage Separator Pump',
    class: 'PUMP - Process Centrifugal',
    system: 'Oil',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 3',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '22/07/2026, 08:50:00',
    observation: 'Flow velocity within operational limits.',
  },
  {
    tag: 'SEP_SEP_HEATER_02',
    fpso: 'SEP',
    name: 'Second Stage Separator Pump',
    class: 'PUMP - Process Centrifugal',
    system: 'Oil',
    criticality: 'Medium',
    objectType: 'NCE',
    condition: 'Critical - Tier 1',
    vibrationStatus: 'Critical',
    lubeOilStatus: 'Critical',
    lastUpdate: '24/07/2026, 06:10:00',
    observation: 'Severe mechanical seal leakage & vibration trip.',
  },
  {
    tag: 'SEP_TURB_GEN_01',
    fpso: 'SEP',
    name: 'Emergency Diesel Generator',
    class: 'GEN - Diesel Engine Generator',
    system: 'Power',
    criticality: 'High',
    objectType: 'SECE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '21/07/2026, 12:00:00',
    observation: 'Weekly auto-start test successful.',
  },
  {
    tag: 'SEP_WATER_TREAT_01',
    fpso: 'SEP',
    name: 'Produced Water Pump A',
    class: 'PUMP - Submersible',
    system: 'Water',
    criticality: 'Low',
    objectType: 'NCE',
    condition: 'Good - Tier 3',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '14/07/2026, 15:30:00',
    observation: 'Oil-in-water monitor calibrated.',
  },
  {
    tag: 'SEP_WATER_TREAT_02',
    fpso: 'SEP',
    name: 'Produced Water Pump B',
    class: 'PUMP - Submersible',
    system: 'Water',
    criticality: 'Low',
    objectType: 'NCE',
    condition: 'Degraded - Tier 2',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Degraded',
    lastUpdate: '12/07/2026, 10:20:00',
    observation: 'Filter clogged, differential pressure high.',
  },
  {
    tag: 'SEP_FLARE_BLOWER_01',
    fpso: 'SEP',
    name: 'Flare Gas Blower A',
    class: 'BLOW - Centrifugal Blower',
    system: 'Gas',
    criticality: 'Medium',
    objectType: 'NCE',
    condition: 'Good - Tier 4',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '23/07/2026, 09:10:00',
    observation: 'VFD speed modulation smooth.',
  },
  {
    tag: 'SEP_FLARE_BLOWER_02',
    fpso: 'SEP',
    name: 'Flare Gas Blower B',
    class: 'BLOW - Centrifugal Blower',
    system: 'Gas',
    criticality: 'Low',
    objectType: 'NCE',
    condition: 'Machine Off',
    vibrationStatus: 'Good',
    lubeOilStatus: 'Good',
    lastUpdate: '05/07/2026, 14:00:00',
    observation: 'Offline for scheduled fan blade cleaning.',
  }
];

const mockHistory = [
  { equipmentTag: 'COCE_TIME_NRS_01', vibrationStatus: 'Good', lubeOilStatus: 'Good', overallCondition: 'Good - Tier 4', changedAt: '2026-03-26T12:00:00Z' },
  { equipmentTag: 'COCE_TIME_NRS_01', vibrationStatus: 'Good', lubeOilStatus: 'Good', overallCondition: 'Good - Tier 3', changedAt: '2026-04-26T12:00:00Z' },
  { equipmentTag: 'COCE_TIME_NRS_01', vibrationStatus: 'Good', lubeOilStatus: 'Good', overallCondition: 'Good - Tier 4', changedAt: '2026-07-23T12:47:04Z' },

  { equipmentTag: 'COCE_TIME_NRS_02', vibrationStatus: 'Critical', lubeOilStatus: 'Good', overallCondition: 'Critical - Tier 1', changedAt: '2026-07-22T14:10:00Z' },
  { equipmentTag: 'CDI_PUMP_OIL_02', vibrationStatus: 'Critical', lubeOilStatus: 'Critical', overallCondition: 'Critical - Tier 1', changedAt: '2026-07-24T13:20:00Z' },
  { equipmentTag: 'SEP_SEP_HEATER_02', vibrationStatus: 'Critical', lubeOilStatus: 'Critical', overallCondition: 'Critical - Tier 1', changedAt: '2026-07-24T06:10:00Z' },
];

const mockReports = [
  {
    equipmentTag: 'COCE_TIME_NRS_02',
    vibrationStatus: 'Critical',
    lubeOilStatus: 'Good',
    overallCondition: 'Critical - Tier 1',
    facility: 'FPSO UNY',
    system: 'Gas',
    tagNumber: 'COCE_TIME_NRS_02',
    cmmsNumber: 'CMMS-9082',
    cof: 'Medium',
    location: 'Module 3',
    machineName: 'MIGC B',
    mcProtection: 'Vibration Trip',
    operatingContext: 'Continuous Gas Export',
    technology: 'Vibration Analysis',
    component: 'Compressor',
    raisedBy: 'Gustavo Silva',
    raisedDate: '2026-07-22',
    targetDate: '2026-08-22',
    shortDescription: 'High vibration alarm on Compressor axial sensors',
    woNumber: '801021309',
    conditionAssessment: 'Based on System 1 trends, abrupt jumps indicate instrumentation failure in axial sensors of Main Gas Compressor C.',
    longDescription: 'Verify sensor fastening, check connection integrity, and perform channel cross-substitution.',
    createdAt: '2026-07-22T14:10:00Z',
  },
  {
    equipmentTag: 'CDI_PUMP_OIL_02',
    vibrationStatus: 'Critical',
    lubeOilStatus: 'Critical',
    overallCondition: 'Critical - Tier 1',
    facility: 'FPSO CDI',
    system: 'Oil',
    tagNumber: 'CDI_PUMP_OIL_02',
    cmmsNumber: 'CMMS-9104',
    cof: 'High',
    location: 'Module 5',
    machineName: 'Crude Pump B',
    mcProtection: 'Temp & Vib Trip',
    operatingContext: 'Crude Offloading',
    technology: 'Vibration Analysis',
    component: 'Thrust Bearing',
    raisedBy: 'Julia Mendes',
    raisedDate: '2026-07-24',
    targetDate: '2026-08-10',
    shortDescription: 'Bearing overheating and particle contamination',
    woNumber: '801021320',
    conditionAssessment: 'Bearing temperature exceeded 95C under load with high metallic particle density.',
    longDescription: 'Perform emergency bearing replacement and lube oil flush.',
    createdAt: '2026-07-24T13:20:00Z',
  }
];

const mockWorkOrders = [
  // UNY FPSO
  {
    reference: '801021309',
    fpso: 'UNY',
    description: 'High vibration alarm on Compressor axial sensors. Verify sensor fastening.',
    priority: 'Accepted',
    status: 'Accepted',
    tagNumber: 'COCE_TIME_NRS_02',
    tagDescription: 'Compressor Performance',
    monitoringTechnique: 'CBM Vibration - Analysis High',
    creationDate: '22/07/2026, 14:10:00',
    dueDate: '25/07/2026, 14:10:00',
    reportId: 1,
    woSite: 'UNY',
    directive: 'VIBRATION SENSOR CHECK',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/H',
    externalSourceId: 'CBM-1089487',
    faultDesc: 'Anomaly: Instrumentation failure in axial sensors.',
    symptom: 'VIB',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021310',
    fpso: 'UNY',
    description: 'Lube oil level drop & slight metallic wear detected.',
    priority: 'Accepted',
    status: 'Accepted',
    tagNumber: 'COCE_TIME_NRS_03',
    tagDescription: 'Compressor Performance',
    monitoringTechnique: 'CBM Lube Oil - Analysis Medium',
    creationDate: '20/07/2026, 09:30:00',
    dueDate: '27/07/2026, 09:30:00',
    woSite: 'UNY',
    directive: 'OIL REPLACE',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-LUB/M',
    externalSourceId: 'CBM-1089555',
    faultDesc: 'Anomaly: Copper and iron particle increase.',
    symptom: 'ELU',
    discovery: '04',
    actionId: '7',
    operationalStatus: '01',
  },
  {
    reference: '801021311',
    fpso: 'UNY',
    description: 'Pressure transmitter readings unstable on discharge header.',
    priority: 'Pending',
    status: 'Pending',
    tagNumber: 'COCE_TIME_NRS_01',
    tagDescription: 'Compressor Performance',
    monitoringTechnique: 'CBM Pressure - Calibration',
    creationDate: '19/07/2026, 11:00:00',
    dueDate: '29/07/2026, 11:00:00',
    woSite: 'UNY',
    directive: 'CALIBRATE TRANSMITTER',
    maintOrg: 'INSTR',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '3',
    faultDesc: 'Pressure transmitter readings unstable.',
    symptom: 'STD',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021312',
    fpso: 'UNY',
    description: 'Routine diagnostic inspection on mechanical seal oil.',
    priority: 'Accepted',
    status: 'Completed',
    tagNumber: 'TURB_METH_GDS_02',
    tagDescription: 'Turbine Performance',
    monitoringTechnique: 'CBM Vibration - Analysis High',
    creationDate: '15/07/2026, 10:00:00',
    dueDate: '21/07/2026, 10:00:00',
    woSite: 'UNY',
    directive: 'INSPECT SEAL OIL',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/H',
    externalSourceId: '4',
    faultDesc: 'Routine diagnostic inspection on mechanical seal oil.',
    symptom: 'ELP',
    discovery: '04',
    actionId: '9',
    operationalStatus: '01',
  },
  {
    reference: '801021313',
    fpso: 'UNY',
    description: 'Lube oil filter delta pressure alarm triggered.',
    priority: 'Pending',
    status: 'Pending',
    tagNumber: 'COCE_TIME_NRS_04',
    tagDescription: 'Compressor Performance',
    monitoringTechnique: 'CBM Delta P - Filter Check',
    creationDate: '18/07/2026, 16:20:00',
    dueDate: '15/08/2026, 16:20:00',
    woSite: 'UNY',
    directive: 'REPLACE FILTER',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-LUB/M',
    externalSourceId: '5',
    faultDesc: 'Lube oil filter delta pressure alarm triggered.',
    symptom: 'PLU',
    discovery: '04',
    actionId: '5',
    operationalStatus: '02',
  },
  {
    reference: '801021314',
    fpso: 'UNY',
    description: 'Stator winding insulation check required.',
    priority: 'Accepted',
    status: 'In Progress',
    tagNumber: 'TURB_METH_GDS_01',
    tagDescription: 'Turbine Performance',
    monitoringTechnique: 'CBM Electrical - Stator',
    creationDate: '24/07/2026, 10:20:15',
    dueDate: '02/08/2026, 10:20:15',
    woSite: 'UNY',
    directive: 'CHECK INSULATION',
    maintOrg: 'ELEC',
    workType: 'CM',
    externalSource: 'CBM-VIB/H',
    externalSourceId: '6',
    faultDesc: 'Stator winding insulation check required.',
    symptom: 'STD',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021315',
    fpso: 'UNY',
    description: 'Impeller wear investigation for Cooling Water Pump B.',
    priority: 'Rejected',
    status: 'Cancelled',
    tagNumber: 'PUMP_COOL_AUX_02',
    tagDescription: 'Cooling Water Pump',
    monitoringTechnique: 'CBM Vibration - Analysis High',
    creationDate: '23/07/2026, 07:15:00',
    dueDate: '24/07/2026, 07:15:00',
    woSite: 'UNY',
    directive: 'IMPELLER OVERHAUL',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/H',
    externalSourceId: '7',
    faultDesc: 'Cavitation noise detected.',
    symptom: 'VIB',
    discovery: '04',
    actionId: '8',
    operationalStatus: '03',
  },

  // CDI FPSO
  {
    reference: '801021320',
    fpso: 'CDI',
    description: 'Emergency bearing replacement and lube oil flush on Crude Oil Transfer Pump B.',
    priority: 'Accepted',
    status: 'In Progress',
    tagNumber: 'CDI_PUMP_OIL_02',
    tagDescription: 'Crude Oil Transfer Pump B',
    monitoringTechnique: 'CBM Vibration - Analysis High',
    creationDate: '24/07/2026, 13:20:00',
    dueDate: '26/07/2026, 13:20:00',
    reportId: 2,
    woSite: 'CDI',
    directive: 'BEARING REPLACEMENT',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/H',
    externalSourceId: '8',
    faultDesc: 'Overheating thrust bearing.',
    symptom: 'HOT',
    discovery: '04',
    actionId: '1',
    operationalStatus: '01',
  },
  {
    reference: '801021321',
    fpso: 'CDI',
    description: 'Vibration spectral analysis on Main Gas Compressor B.',
    priority: 'Accepted',
    status: 'Accepted',
    tagNumber: 'CDI_COMP_MAIN_02',
    tagDescription: 'Main Gas Compressor B',
    monitoringTechnique: 'CBM Vibration - Spectral',
    creationDate: '20/07/2026, 18:10:00',
    dueDate: '30/07/2026, 18:10:00',
    woSite: 'CDI',
    directive: 'SPECTRAL DIAGNOSTIC',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/M',
    externalSourceId: '9',
    faultDesc: 'Spectral spike at 2X RPM.',
    symptom: 'VIB',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021322',
    fpso: 'CDI',
    description: 'Dehydration and lube oil purification on Main Power Generator Turb-B.',
    priority: 'Pending',
    status: 'Pending',
    tagNumber: 'CDI_GEN_TURB_02',
    tagDescription: 'Main Power Generator Turb-B',
    monitoringTechnique: 'CBM Lube Oil - Moisture Check',
    creationDate: '16/07/2026, 11:30:00',
    dueDate: '10/08/2026, 11:30:00',
    woSite: 'CDI',
    directive: 'OIL PURIFICATION',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-LUB/M',
    externalSourceId: '10',
    faultDesc: 'Water content exceeds limit.',
    symptom: 'WTR',
    discovery: '04',
    actionId: '7',
    operationalStatus: '01',
  },
  {
    reference: '801021323',
    fpso: 'CDI',
    description: 'Post-commissioning check for Main Gas Compressor A.',
    priority: 'Accepted',
    status: 'Completed',
    tagNumber: 'CDI_COMP_MAIN_01',
    tagDescription: 'Main Gas Compressor A',
    monitoringTechnique: 'CBM Performance Test',
    creationDate: '22/07/2026, 15:45:00',
    dueDate: '23/07/2026, 15:45:00',
    woSite: 'CDI',
    directive: 'PERFORMANCE VERIFY',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '11',
    faultDesc: 'Recommissioning verify.',
    symptom: 'OK',
    discovery: '04',
    actionId: '9',
    operationalStatus: '01',
  },
  {
    reference: '801021324',
    fpso: 'CDI',
    description: 'Alignment laser check on Crude Oil Transfer Pump A.',
    priority: 'Accepted',
    status: 'In Progress',
    tagNumber: 'CDI_PUMP_OIL_01',
    tagDescription: 'Crude Oil Transfer Pump A',
    monitoringTechnique: 'CBM Laser Alignment',
    creationDate: '17/07/2026, 14:00:00',
    dueDate: '28/07/2026, 14:00:00',
    woSite: 'CDI',
    directive: 'LASER ALIGNMENT',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '12',
    faultDesc: 'Laser alignment routine.',
    symptom: 'MIS',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021325',
    fpso: 'CDI',
    description: 'High-pressure seal flushing for Water Injection Pump 1.',
    priority: 'Accepted',
    status: 'Completed',
    tagNumber: 'CDI_WATER_INJ_01',
    tagDescription: 'Water Injection Pump 1',
    monitoringTechnique: 'CBM Pressure Check',
    creationDate: '24/07/2026, 16:00:00',
    dueDate: '25/07/2026, 16:00:00',
    woSite: 'CDI',
    directive: 'SEAL FLUSH',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '13',
    faultDesc: 'High-pressure seal flushing.',
    symptom: 'OK',
    discovery: '04',
    actionId: '9',
    operationalStatus: '01',
  },
  {
    reference: '801021326',
    fpso: 'CDI',
    description: 'Offline preservation inspection for Water Injection Pump 2.',
    priority: 'Pending',
    status: 'Pending',
    tagNumber: 'CDI_WATER_INJ_02',
    tagDescription: 'Water Injection Pump 2',
    monitoringTechnique: 'CBM Preservation Check',
    creationDate: '10/07/2026, 08:00:00',
    dueDate: '10/08/2026, 08:00:00',
    woSite: 'CDI',
    directive: 'PRESERVATION CHECK',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '14',
    faultDesc: 'Offline unit check.',
    symptom: 'OFF',
    discovery: '04',
    actionId: '9',
    operationalStatus: '01',
  },

  // SEP FPSO
  {
    reference: '801021330',
    fpso: 'SEP',
    description: 'Mechanical seal replacement on Second Stage Separator Pump.',
    priority: 'Accepted',
    status: 'In Progress',
    tagNumber: 'SEP_SEP_HEATER_02',
    tagDescription: 'Second Stage Separator Pump',
    monitoringTechnique: 'CBM Vibration - Analysis High',
    creationDate: '24/07/2026, 06:10:00',
    dueDate: '27/07/2026, 06:10:00',
    woSite: 'SEP',
    directive: 'SEAL REPLACEMENT',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/H',
    externalSourceId: '15',
    faultDesc: 'Severe mechanical seal leakage.',
    symptom: 'LEAK',
    discovery: '04',
    actionId: '1',
    operationalStatus: '01',
  },
  {
    reference: '801021331',
    fpso: 'SEP',
    description: 'Piston rod packing seal temperature check on Booster Compressor B.',
    priority: 'Accepted',
    status: 'Accepted',
    tagNumber: 'SEP_COMP_BOOST_02',
    tagDescription: 'Gas Booster Compressor B',
    monitoringTechnique: 'CBM Thermography - Rod Seal',
    creationDate: '18/07/2026, 17:40:00',
    dueDate: '28/07/2026, 17:40:00',
    woSite: 'SEP',
    directive: 'PACKING SEAL CHECK',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/M',
    externalSourceId: '16',
    faultDesc: 'Elevated rod temperature.',
    symptom: 'HOT',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021332',
    fpso: 'SEP',
    description: 'Filter replacement on Produced Water Pump B.',
    priority: 'Pending',
    status: 'Pending',
    tagNumber: 'SEP_WATER_TREAT_02',
    tagDescription: 'Produced Water Pump B',
    monitoringTechnique: 'CBM Delta P - Filter',
    creationDate: '12/07/2026, 10:20:00',
    dueDate: '12/08/2026, 10:20:00',
    woSite: 'SEP',
    directive: 'REPLACE FILTER',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-LUB/M',
    externalSourceId: '17',
    faultDesc: 'High differential pressure across filter.',
    symptom: 'CLOG',
    discovery: '04',
    actionId: '5',
    operationalStatus: '01',
  },
  {
    reference: '801021333',
    fpso: 'SEP',
    description: 'Valve timing diagnostic on Gas Booster Compressor A.',
    priority: 'Accepted',
    status: 'Completed',
    tagNumber: 'SEP_COMP_BOOST_01',
    tagDescription: 'Gas Booster Compressor',
    monitoringTechnique: 'CBM Reciprocating Diagnostic',
    creationDate: '23/07/2026, 11:15:00',
    dueDate: '24/07/2026, 11:15:00',
    woSite: 'SEP',
    directive: 'VALVE TIMING CHECK',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '18',
    faultDesc: 'Valve timing within specs.',
    symptom: 'OK',
    discovery: '04',
    actionId: '9',
    operationalStatus: '01',
  },
  {
    reference: '801021334',
    fpso: 'SEP',
    description: 'Coupling inspection on First Stage Separator Pump.',
    priority: 'Accepted',
    status: 'In Progress',
    tagNumber: 'SEP_SEP_HEATER_01',
    tagDescription: 'First Stage Separator Pump',
    monitoringTechnique: 'CBM Vibration - Analysis High',
    creationDate: '22/07/2026, 08:50:00',
    dueDate: '31/07/2026, 08:50:00',
    woSite: 'SEP',
    directive: 'INSPECT COUPLING',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '19',
    faultDesc: 'Coupling elastomeric check.',
    symptom: 'VIB',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021335',
    fpso: 'SEP',
    description: 'Emergency Diesel Generator battery bank voltage test.',
    priority: 'Accepted',
    status: 'Completed',
    tagNumber: 'SEP_TURB_GEN_01',
    tagDescription: 'Emergency Diesel Generator',
    monitoringTechnique: 'CBM Electrical - Battery',
    creationDate: '21/07/2026, 12:00:00',
    dueDate: '22/07/2026, 12:00:00',
    woSite: 'SEP',
    directive: 'BATTERY TEST',
    maintOrg: 'ELEC',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '20',
    faultDesc: 'Battery bank voltage normal.',
    symptom: 'OK',
    discovery: '04',
    actionId: '9',
    operationalStatus: '01',
  },
  {
    reference: '801021336',
    fpso: 'SEP',
    description: 'VFD drive harmonics check for Flare Gas Blower A.',
    priority: 'Accepted',
    status: 'In Progress',
    tagNumber: 'SEP_FLARE_BLOWER_01',
    tagDescription: 'Flare Gas Blower A',
    monitoringTechnique: 'CBM Electrical - VFD',
    creationDate: '23/07/2026, 09:10:00',
    dueDate: '01/08/2026, 09:10:00',
    woSite: 'SEP',
    directive: 'VFD HARMONICS CHECK',
    maintOrg: 'ELEC',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '21',
    faultDesc: 'VFD modulation check.',
    symptom: 'ELEC',
    discovery: '04',
    actionId: '6',
    operationalStatus: '01',
  },
  {
    reference: '801021337',
    fpso: 'SEP',
    description: 'Fan blade balancing for Flare Gas Blower B.',
    priority: 'Rejected',
    status: 'Cancelled',
    tagNumber: 'SEP_FLARE_BLOWER_02',
    tagDescription: 'Flare Gas Blower B',
    monitoringTechnique: 'CBM Dynamic Balancing',
    creationDate: '05/07/2026, 14:00:00',
    dueDate: '06/07/2026, 14:00:00',
    woSite: 'SEP',
    directive: 'DYNAMIC BALANCING',
    maintOrg: 'MECHTS',
    workType: 'CM',
    externalSource: 'CBM-VIB/L',
    externalSourceId: '22',
    faultDesc: 'Offline unit, deferred.',
    symptom: 'OFF',
    discovery: '04',
    actionId: '8',
    operationalStatus: '03',
  }
];

export async function seed() {
  console.log('Clearing existing records for seed refresh...');
  await db.delete(workOrders);
  await db.delete(analysisReports);
  await db.delete(equipmentHistory);
  await db.delete(equipments);

  console.log('Seeding database with expanded datasets (25+ items per table)...');
  await db.insert(equipments).values(initialEquipments);
  await db.insert(equipmentHistory).values(mockHistory);
  
  // Insert reports first and get their inserted IDs
  const insertedReports = await db.insert(analysisReports).values(mockReports).returning();
  
  // Update reportId references in mockWorkOrders
  const updatedWorkOrders = mockWorkOrders.map((wo) => {
    if (wo.reference === '801021309' && insertedReports[0]) {
      return { ...wo, reportId: insertedReports[0].id };
    }
    if (wo.reference === '801021320' && insertedReports[1]) {
      return { ...wo, reportId: insertedReports[1].id };
    }
    return { ...wo, reportId: null };
  });

  await db.insert(workOrders).values(updatedWorkOrders);
  console.log('Seeding completed successfully with 25+ records per table.');
}
