// ISO 14224 & SLB CBM Failure Modes Taxonomy

export const FAILURE_MODE_OPTIONS = [
  'AIR - Abnormal Instrument Reading',
  'BRD - Breakdown',
  'ELP - External Leakage - process medium',
  'ELU - External Leakage - Utility Medium',
  'ERO - Erratic Output',
  'FTS - Failure To Start On Demand',
  'HIO - High Output',
  'INL - Internal Leakage',
  'LOO - Low Output',
  'NOI - Noise',
  'OHE - Overheating',
  'PDE - Parameter Deviation',
  'PLU - Plugged / Choked',
  'STD - Structural Deficiency',
  'STP - Failure To Stop On Demand',
  'UST - Spurious Stop',
  'VIB - Vibration',
  'ELF - External Leakage - Fuel',
];

export const FAILURE_MECHANISM_SUBDIVISION_OPTIONS = [
  'Mechanical Failure - Leakage',
  'Mechanical Failure - Vibration',
  'Mechanical Failure - Clearance',
  'Mechanical Failure - Unbalance',
  'Mechanical Failure - Misalignment',
  'Mechanical Failure - Deformation',
  'Mechanical Failure - Looseness',
  'Mechanical Failure - Sticking',
  'Material Failure - Cavitation',
  'Material Failure - Corrosion',
  'Material Failure - Erosion',
  'Material Failure - Wear',
  'Material Failure - Breakage',
  'Material Failure - Fatigue',
  'Material Failure - Overheating',
  'Material Failure - Burst',
  'Instrument Failure - Control Failure',
  'Instrument Failure - No Signal/Indication/Alarm',
  'Instrument Failure - Faulty Signal/Indication/Alarm',
  'Instrument Failure - Out of Adjustment',
  'Instrument Failure - Software Error',
  'Instrument Failure - Common Cause/Common Mode Failure',
  'Electrical Failure - Short Circuiting',
  'Electrical Failure - Open Circuit',
  'Electrical Failure - No Power/Voltage',
  'Electrical Failure - Faulty Power/Voltage',
  'Electrical Failure - Earth/Isolation Fault',
  'External Influence - Blockage/Plugged',
  'External Influence - Contamination',
  'External Influence - Miscellaneous External Influences',
  'Miscellaneous - No Cause Found',
  'Miscellaneous - Combined Causes',
  'Miscellaneous - Other',
  'Miscellaneous - Unknown',
];

export const EQUIPMENT_CLASS_OPTIONS = [
  'Centrifugal Compressor',
  'Centrifugal Pump',
  'Gas Turbine',
  'Reciprocating Compressor',
  'Screw Compressor',
];

export const TAXONOMY_DATA: Record<string, Record<string, string[]>> = {
  'Centrifugal Compressor': {
    'Power Transmission': [
      'Coupling to the Driver',
      'Coupling to the Driven Unit',
      'Lubrication',
      'Seals',
      'Bearings',
      'Gearbox / Variable Drive',
      'Belt / Sheave',
    ],
    'Compressor': [
      'Casing',
      'Rotor with Impellers',
      'Balance Piston',
      'Interstage Seals',
      'Thrust Bearing',
      'Radial Bearing',
      'Shaft Seals',
      'Internal Piping',
      'Valves',
      'Antysurge System',
    ],
    'Control and Monitoring': [
      'Actuating Device',
      'Control Unit',
      'Cables and Junction Boxes',
      'Internal Power Supply',
      'Monitoring',
      'Sensors',
      'Valves',
      'Wiring',
      'Piping',
      'Seals',
    ],
    'Lubrication System': [
      'Oil Tank with Heating System',
      'Pump',
      'Motor',
      'Check Valves',
      'Coolers',
      'Filters',
      'Piping',
      'Valves',
      'Lube Oil',
    ],
    'Shaft Seal System': [
      'Oil Tank with Heating',
      'Reservoir',
      'Pump',
      'Motor',
      'Gear',
      'Filters',
      'Valves',
      'Seal Oil',
      'Dry Gas Seal',
      'Mechanical Seal',
      'Scrubber',
    ],
    'Miscellaneous': [
      'Base Frame',
      'Piping, Pipe Support and Bellows',
      'Control Valves',
      'Isolation Valves',
      'Check Valves',
      'Coolers',
      'Silencers',
      'Purge Air',
      'Flange Joints',
    ],
  },
  'Screw Compressor': {
    'Power Transmission': [
      'Coupling to the Driver',
      'Coupling to the Driven Unit',
      'Lubrication',
      'Seals',
      'Bearings',
      'Gearbox / Variable Drive',
      'Belt / Sheave',
    ],
    'Compressor': [
      'Casing',
      'Female Rotor',
      'Male Rotor',
      'Thrust Bearing',
      'Radial Bearing',
      'Shaft Seals',
      'Internal Piping',
      'Valves',
      'Spillback System',
    ],
    'Control and Monitoring': [
      'Actuating Device',
      'Control Unit',
      'Cables and Junction Boxes',
      'Internal Power Supply',
      'Monitoring',
      'Sensors',
      'Valves',
      'Wiring',
      'Piping',
      'Seals',
    ],
    'Lubrication System': [
      'Oil Tank with Heating System',
      'Pump',
      'Motor',
      'Check Valves',
      'Coolers',
      'Filters',
      'Piping',
      'Valves',
      'Lube Oil',
    ],
    'Shaft Seal System': [
      'Oil Tank with Heating',
      'Reservoir',
      'Pump',
      'Motor',
      'Gear',
      'Filters',
      'Valves',
      'Seal Oil',
      'Dry Gas Seal',
      'Mechanical Seal',
      'Scrubber',
    ],
    'Miscellaneous': [
      'Base Frame',
      'Piping, Pipe Support and Bellows',
      'Control Valves',
      'Isolation Valves',
      'Check Valves',
      'Coolers',
      'Silencers',
      'Purge Air',
      'Flange Joints',
    ],
  },
  'Reciprocating Compressor': {
    'Power Transmission': [
      'Coupling to the Driver',
      'Coupling to the Driven Unit',
      'Lubrication',
      'Seals',
      'Bearings',
      'Gearbox / Variable Drive',
      'Belt / Sheave',
    ],
    'Compressor': [
      'Casing',
      'Piston',
      'Cylinder Line',
      'Packing',
      'Bearing',
      'Shaft Seals',
      'Internal Piping',
      'Valves',
      'Spillback System',
    ],
    'Control and Monitoring': [
      'Actuating Device',
      'Control Unit',
      'Cables and Junction Boxes',
      'Internal Power Supply',
      'Monitoring',
      'Sensors',
      'Valves',
      'Wiring',
      'Piping',
      'Seals',
    ],
    'Lubrication System': [
      'Oil Tank with Heating System',
      'Pump',
      'Motor',
      'Check Valves',
      'Coolers',
      'Filters',
      'Piping',
      'Valves',
      'Lube Oil',
    ],
    'Shaft Seal System': [
      'Oil Tank with Heating',
      'Reservoir',
      'Pump',
      'Motor',
      'Gear',
      'Filters',
      'Valves',
      'Seal Oil',
      'Dry Gas Seal',
      'Mechanical Seal',
      'Scrubber',
    ],
    'Miscellaneous': [
      'Base Frame',
      'Piping, Pipe Support and Bellows',
      'Control Valves',
      'Isolation Valves',
      'Check Valves',
      'Coolers',
      'Silencers',
      'Purge Air',
      'Flange Joints',
    ],
  },
  'Centrifugal Pump': {
    'Power Transmission': [
      'Coupling to the Driver',
      'Coupling to the Driven Unit',
      'Lubrication',
      'Seals',
      'Bearings',
      'Gearbox / Variable Drive',
      'Belt / Sheave',
    ],
    'Pump Unit': [
      'Support',
      'Casing',
      'Impeller',
      'Shaft',
      'Thrust Bearing',
      'Radial Bearing',
      'Seals',
      'Piping',
      'Valves',
    ],
    'Control and Monitoring': [
      'Actuating Device',
      'Control Unit',
      'Cables and Junction Boxes',
      'Internal Power Supply',
      'Monitoring',
      'Sensors',
      'Valves',
      'Wiring',
      'Piping',
      'Seals',
    ],
    'Lubrication System': [
      'Reservoir',
      'Pump',
      'Motor',
      'Cooler',
      'Filter',
      'Piping',
      'Valves',
      'Lube Oil',
      'Seals',
    ],
    'Miscellaneous': [
      'Cyclone Separator',
      'Cooling/Heating System',
      'Purge Air',
      'Flange Joints',
    ],
  },
  'Gas Turbine': {
    'Starting System': [
      'Starting Motor',
      'Start Control',
      'Piping',
      'Filter',
      'Valve',
      'Pump',
      'Start Energy - Battery, Air',
    ],
    'Air Intake': [
      'Air Cooling',
      'Anti-icing',
      'Filters',
      'Intake Duct',
      'Inlet Vanes',
    ],
    'Combustion System': [
      'Combustor',
      'Fuel Nozzles',
      'Seals',
    ],
    'Compressor': [
      'Rotor',
      'Stator',
      'Cooling System',
      'VGV System',
      'Anti-surge Valve',
      'Aux. Bleeding System',
      'Anti-icing Valve',
      'Casing',
      'Radial Bearing',
      'Thrust Bearing',
      'Seals',
      'Piping',
    ],
    'Power Turbine HP Turbine': [
      'Rotor',
      'Stator',
      'Casing',
      'Radial Bearing',
      'Thrust Bearing',
      'Seals',
      'Valves',
      'Piping',
    ],
    'Control and Monitoring': [
      'Control Unit',
      'Sensors',
      'Wires',
      'Actuating Device',
      'Monitoring',
      'Valves',
      'Internal Power Supply',
      'Seals',
    ],
    'Lubrication System': [
      'Heater',
      'Reservoir',
      'Pump',
      'Motor',
      'Filter',
      'Temperature Control',
      'Valves',
      'Piping',
      'Oil Cooler',
      'Oil',
      'Sensors',
      'Wires',
    ],
    'Fuel System': [
      'Fuel Control',
      'Piping',
      'Valves',
      'Pump/Gas Compressor',
      'Filters/Separators',
      'Wires',
      'Fuel Properties Measurement',
    ],
    'Water/Steam Injection': [
      'Pump',
      'Piping',
      'Valves',
      'Filters',
      'Seals',
      'Wires',
    ],
    'Fire and Gas Protection': [
      'Control Unit',
      'Pipes',
      'Valves',
      'Sensors',
      'Wires',
      'Tanks/Storage',
    ],
    'Acessory Drive': [
      'Gearbox',
      'Bearing',
      'Seals',
      'Casing',
    ],
    'Exhaust': [
      'Diffuser',
      'Exhaust collector',
      'Compensator/bellows',
      'Ducting',
      'Emission monitoring',
      'Silencer',
      'Thrust Bearing',
      'Valves',
      'Waste Heat Recovery Unit',
    ],
    'Miscellaneous': [
      'Enclosure',
      'Hood',
      'Purge air',
      'Flange Joints',
      'Ventilation Fan',
      'Water-wash System',
    ],
  },
};
